# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nushell = {
    pname = "nushell";
    version = "913c2b8d1c02bf349b7ba27c14ebfeedf4aa65c4";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "nushell";
      rev = "913c2b8d1c02bf349b7ba27c14ebfeedf4aa65c4";
      fetchSubmodules = false;
      sha256 = "sha256-D79wUHHVXQH8tEvzF3+hSPfdk/FH5QPMghsEpLm/KoE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nushell-913c2b8d1c02bf349b7ba27c14ebfeedf4aa65c4/Cargo.lock;
      outputHashes = {
        "reedline-0.27.1" = "sha256-cdpkj8bALD0pmMjX6ziCQepyPpjplv/CcX6YrkwxeAM=";
      };
    };
    date = "2023-12-25";
  };
}
