# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nushell = {
    pname = "nushell";
    version = "4073783d6e63f31ecbfd5925bff218d48f93b0b9";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "nushell";
      rev = "4073783d6e63f31ecbfd5925bff218d48f93b0b9";
      fetchSubmodules = false;
      sha256 = "sha256-Gv7YCr2B+xaQCs4k7iUwnRNmRziKzeHCz7S3gtXPUAY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nushell-4073783d6e63f31ecbfd5925bff218d48f93b0b9/Cargo.lock;
      outputHashes = {
        "reedline-0.29.0" = "sha256-vRU4uc3pXdY5ypp6TBZiPwgkrHriV61B2HAHfLvRRQc=";
      };
    };
    date = "2024-02-14";
  };
}
