# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nushell = {
    pname = "nushell";
    version = "64695cd67c0ccbcba3a7aadbfb47981e3011770b";
    src = fetchFromGitHub {
      owner = "nushell";
      repo = "nushell";
      rev = "64695cd67c0ccbcba3a7aadbfb47981e3011770b";
      fetchSubmodules = false;
      sha256 = "sha256-SXIuXZgEFwpWrigLBmLfuNYYQR59gq/bCmBKXv1Thw8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nushell-64695cd67c0ccbcba3a7aadbfb47981e3011770b/Cargo.lock;
      outputHashes = {
        "reedline-0.27.1" = "sha256-8vrCaldEYdI3R7pIXQ+L3KI3JHYRa3xAiFAt3EmP24A=";
      };
    };
    date = "2023-12-30";
  };
}
