name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "npins/**"
      - "flake.*"
      - "nushell.nix"
      - "tree-sitter-nu.nix"
jobs:
  build:
    strategy:
      matrix:
        package:
          [
            nushell,
            nu_plugin_formats,
            nu_plugin_gstat,
            nu_plugin_inc,
            nu_plugin_query,
            nu_plugin_polars,
            tree-sitter-nu,
          ]
        os: [linux, darwin]
        arch: [aarch64, x86_64]
        exclude:
          - os: darwin
            arch: aarch64
      fail-fast: false
    runs-on: ${{ matrix.os == 'linux' && 'ubuntu-latest' || 'macos-latest' }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup QEMU
        if: matrix.os == 'linux' && matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: arm64
      - uses: cachix/install-nix-action@v31.6.1
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v16
        with:
          name: nushell-nightly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#${{ matrix.package }} --option system ${{ matrix.arch }}-${{ matrix.os }}
