name: "Update npins sources"
on:
  workflow_dispatch:
  schedule:
    # every hour
    - cron: "0 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}
      - uses: cachix/install-nix-action@v31.6.1
      - name: Setup git
        run: |
          git config user.name 'npins updater'
          git config user.email 'noreply@github.com'
      - name: Update nushell
        run: |
          nix run .#update
      - name: Push changes
        run: git push
